### ISSUE TITLE
Not enough information to infer type variable ResultType

### ISSUE THREAD

**Issue by minion06** [AkshayChordiya/News#24]
In NewsRepository  emit(ViewState.loading()) is showing an issue

Not enough information to infer type variable ResultType

**Comment by AkshayChordiya** [comment]
Generally this issue happens because code hasn't been compiled correctly yet; doing a gradle sync should solve that issue or maybe a clean build after that.
Let me know if that works :)

**Comment by AkshayChordiya** [comment]
Closing the issue due to in-activity. Please feel free to open it again if the issue persists
