### ISSUE TITLE
Two Incorrect Configurations found in app/build.gradle

### ISSUE THREAD

**Issue by iNoles** [AkshayChordiya/News#25]
1) implementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutinesVersion" needs to be testImplementation. As for right now, it is very unneeded libraries because it wouldn't break anything.

2) implementation "androidx.arch.core:core-testing:$lifecycleVersion" needs to be testImplementation too.

**Comment by AkshayChordiya** [comment]
Thanks for pointing it out. I recently noticed the same. I'll push fixes to both the issues in couple of days
