### ISSUE TITLE
Room's Insert with List gives incorrect values

### ISSUE THREAD

**Issue by iNoles** [AkshayChordiya/News#27]
If you are unit testing on 
```
@Insert
 fun insertArticles(articles: List<NewsArticles>): List<Long>
```
it always output as [].

**Comment by AkshayChordiya** [comment]
Yeah I think it's because of in-memory database 🤔

**Comment by iNoles** [comment]
I found another way of doing it. https://code.luasoftware.com/tutorials/android/android-room-batch-insert-or-update/
