### ISSUE TITLE
Suggerstion: Replace Gson with Kotlinx Serialization

### ISSUE THREAD

**Issue by iNoles** [AkshayChordiya/News#31]
Gson is not really Kotlin friendly because it doesn't understand about Kotlin null safe types. 

Moshi is made by Square and have kotlin support by codegen or reflect which requires kapt.

JetBrains made own json serialization library. https://github.com/Kotlin/kotlinx.serialization it have own compiler plugins for it.

**Comment by AkshayChordiya** [comment]
Yeah thanks for bringing this up. I'll try to do this sometime soon :)

**Comment by nkrebs13** [comment]
I'd like to try my hand at this! I'll try to get a PR out this weekend at some point :)

**Comment by AkshayChordiya** [comment]
Thanks @nkrebs13. I'll assign the issue to you then :)
