### ISSUE TITLE
NetworkBoundResource.asFlow() is called multiple times

### ISSUE THREAD

**Issue by kefasjwiryadi** [AkshayChordiya/News#38]
After 5 seconds of no active observers for `NewsArticleViewModel.newsArticles` (device locked) and `NewsActivity` re-observe the `newsArticles` (device unlocked), `NetworkBoundResource.asFlow()` is called again. 

If I change the `emitAll(loadFromDb().map { ViewState.success(it) })` into `emit(loadFromDb().map { ViewState.success(it) }.first())`, `NetworkBoundResource.asFlow()` is not called.

**Comment by AkshayChordiya** [comment]
Fixed with https://github.com/AkshayChordiya/News/commit/d445be8a0d139527f15656a1c7b5f238fd1b05c7
