### ISSUE TITLE
APP NOT OPENING. ERROR AT GRADLE

### ISSUE THREAD

**Issue by kanakapalli** [AkshayChordiya/News#42]
![image](https://user-images.githubusercontent.com/38519098/87329949-70961f00-c555-11ea-804b-5adf9ecdda82.png)

**Comment by AkshayChordiya** [comment]
You are missing the API key. Follow the steps mentioned in the readme and create your `credentials.properties` with API key.
https://github.com/AkshayChordiya/News/blob/master/README.md#api-key-
